version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    env_file:
      - ./bitcoinTracker/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - wallet
  wallet:
    image: dockermgt/my-wallet-service
    ports:
      - 8080:8080
volumes:
  postgres_data: